name: Directors Gates
on: { workflow_call: {} }
jobs:
  gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secret scan (light)
        run: |
          ! grep -RInE '\bsk-[A-Za-z0-9_-]{20,}\b' . || { echo "OpenAI-like key found"; exit 1; }
          ! grep -RInE 'API_KEY=|SECRET=|TOKEN=' . || { echo "Generic secret token marker found"; exit 1; }
      - name: Port guard (allow only 8787/5173)
        run: |
          ! grep -RInE '127\.0\.0\.1:(?!8787|5173)\d{4}' . || { echo "Forbidden local port used"; exit 1; }
      - name: Constitution present
        run: test -f docs/NXT_GROUP_CONSTITUTION_v6.md
